version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=blog
    volumes:
      - /var/lib/mysql
      - ./blog.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: doantrihung/socket-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql